name: Build AIC8800 DKMS Debian Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: ubuntu:26.04

    steps:

      - name: Install dependencies
        run: |
          apt update
          apt install -y \
            git \
            build-essential \
            devscripts \
            debhelper \
            dh-exec \
            dh-dkms \
            dkms \
            fakeroot \
            quilt \
            dos2unix \
            gcc-aarch64-linux-gnu \
            ca-certificates

      - name: Download AIC8800 source
        run: |
          git clone https://github.com/radxa-pkg/aic8800.git aic8800

      - name: Prepare source
        run: |
          cd aic8800

          # 修复源码换行
          find . \
            \( -name "*.c" -o -name "*.h" -o -name "*.patch" \) \
            -exec dos2unix {} \;

          # 删除USB相关patch，避免版本冲突
          sed -i '/fix-usb/d' debian/patches/series || true

          # 跳过ARM64测试程序导致的打包检查失败
          printf '\n' >> debian/rules

          printf 'override_dh_dwz:\n' >> debian/rules
          printf '\t@echo "Skip dh_dwz"\n' >> debian/rules

          printf '\n' >> debian/rules

          printf 'override_dh_strip:\n' >> debian/rules
          printf '\t@echo "Skip dh_strip"\n' >> debian/rules

          printf '\n' >> debian/rules

          printf 'override_dh_shlibdeps:\n' >> debian/rules
          printf '\t@echo "Skip dh_shlibdeps"\n' >> debian/rules

          chmod +x debian/rules

      - name: Build Debian package
        run: |
          cd aic8800

          dpkg-buildpackage \
            -us \
            -uc \
            -b \
            -d

      - name: Collect packages
        run: |
          mkdir output

          find .. \
            -name "*.deb" \
            -exec cp {} output/ \;

          ls -lh output

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: aic8800-dkms
          path: output/*.deb
