name: Build AIC8800 PCIe DKMS Debian Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    container:
      image: ubuntu:26.04

    steps:
      - name: Install build tools
        run: |
          apt update
          apt install -y \
            git \
            build-essential \
            devscripts \
            debhelper \
            dh-exec \
            dos2unix \
            fakeroot \
            quilt \
            dkms \
            dh-dkms \
            gcc-aarch64-linux-gnu \
            ca-certificates

      - name: Clone AIC8800 source
        run: |
          git clone https://github.com/radxa-pkg/aic8800.git aic8800

      - name: Prepare source
        run: |
          cd aic8800

          # 修复换行
          find . \
            \( -name "*.c" -o -name "*.h" -o -name "*.patch" \) \
            -exec dos2unix {} \;

          # PCIe 不需要 USB patch
          sed -i '/fix-usb/d' debian/patches/series

          # 跳过 dh_dwz，避免 ARM64 测试程序导致 objcopy 失败
          printf '\noverride_dh_dwz:\n' >> debian/rules
          printf '\t@echo "Skip dh_dwz"\n' >> debian/rules

      - name: Build Debian package
        run: |
          cd aic8800

          dpkg-buildpackage \
            -us \
            -uc \
            -b \
            -d

      - name: Collect packages
        run: |
          mkdir output

          find .. -name "*.deb" -exec cp {} output/ \;

          ls -lh output

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: aic8800-pcie-dkms
          path: output/*.deb
